import React from 'react';
import { Scale, Calendar, HelpCircle, AlertCircle, Copy } from 'lucide-react';

interface TermsViewProps {
  brandName?: string;
  footerCopyrightName?: string;
}

export default function TermsView({
  brandName = 'FreeCSS',
  footerCopyrightName = 'cssfonts.net'
}: TermsViewProps) {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <div id="terms-of-use-view" className="py-8 font-sans max-w-4xl mx-auto">
      {/* Terms Header */}
      <div className="mb-12 text-center sm:text-left">
        <div className="inline-flex items-center gap-1.5 text-[10px] font-bold text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/30 px-2.5 py-1 rounded-lg border border-emerald-100 dark:border-emerald-900/30 uppercase tracking-widest font-mono mb-4">
          <Scale className="h-3 w-3" /> Regulatory Standards
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-slate-900 dark:text-white uppercase tracking-tight font-display">
          Terms of Use
        </h1>
        <div className="flex flex-wrap items-center justify-center sm:justify-start gap-3 mt-3 text-xs text-slate-500 dark:text-slate-400 font-mono">
          <span className="flex items-center gap-1">
            <Calendar className="h-3.5 w-3.5" /> Published: {currentDate}
          </span>
          <span className="hidden sm:inline">•</span>
          <span>Suite: {footerCopyrightName}</span>
        </div>
      </div>

      {/* Terms main elements */}
      <div className="space-y-8 text-sm text-slate-600 dark:text-slate-350 leading-relaxed font-sans">
        
        <p className="text-base text-slate-700 dark:text-slate-200">
          Welcome to <strong>{brandName}</strong>. Please review these Terms of Use ("Terms") carefully. By visiting, using, copy-pasting code fragments, or triggering our typography tools, you agree to comply with and be bound by these criteria.
        </p>

        {/* Term 1 */}
        <div className="p-5 sm:p-6 rounded-2xl border border-slate-200 dark:border-slate-850 bg-white dark:bg-slate-950">
          <h2 className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-900 dark:text-white font-display mb-3">
            <Copy className="h-4.5 w-4.5 text-indigo-500" /> 1. License of Assets & Code Snippets
          </h2>
          <p>
            All CSS declarations, style setups, code fragments, sitemaps, splay parameters, and safe-stack code lists generated by the suite are designed for rapid web creation. You are granted a worldwide, royalty-free, non-exclusive, perpetual license to copy, modify, and integrate these generated assets into personal, commercial, or open-source websites. We require absolutely no credits or back-links.
          </p>
        </div>

        {/* Term 2 */}
        <div className="p-5 sm:p-6 rounded-2xl border border-slate-200 dark:border-slate-850 bg-white dark:bg-slate-950">
          <h2 className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-900 dark:text-white font-display mb-3">
            <HelpCircle className="h-4.5 w-4.5 text-indigo-500" /> 2. Typography Licensing & Google Fonts
          </h2>
          <p>
            This application facilitates previewing standard system fallbacks and public Google Web Fonts. System fonts depend on preexisting visitor device libraries. Google Web Fonts operate under their respective Open Source, SIL Open Font License (OFL), or Apache terms. You are solely responsible for ensuring your live deployments align with individual typeface copyrights.
          </p>
        </div>

        {/* Term 3 */}
        <div className="p-5 sm:p-6 rounded-2xl border border-slate-200 dark:border-slate-850 bg-white dark:bg-slate-950">
          <h2 className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-slate-900 dark:text-white font-display mb-3">
            <AlertCircle className="h-4.5 w-4.5 text-indigo-500" /> 3. Liability & Performance Disclaimer
          </h2>
          <p className="mb-2">
            The service is provided on an "as-is" and "as-available" basis without guarantees of any kind, either express or implied.
          </p>
          <ul className="list-disc pl-5 space-y-2 text-xs text-slate-550 dark:text-slate-400">
            <li>
              We represent safety rating scores and OS rendering percentage figures as educational estimates based on historical standards. Actual rendering depends on variable user configuration states.
            </li>
            <li>
              We do not warrant that remote web typographies retrieved from external servers remain universally online, or that service feeds won't encounter occasional connection disruptions.
            </li>
          </ul>
        </div>

        {/* Term 4 */}
        <div className="p-5 sm:p-6 rounded-2xl border border-slate-200 dark:border-slate-850 bg-white dark:bg-slate-950">
          <h2 className="text-xs font-black uppercase tracking-widest text-slate-900 dark:text-white font-display mb-3">
            4. Prohibited Behaviors
          </h2>
          <p>
            You agree not to configure bots, automation scripts, scrapers, or other denial-of-service programs to query our endpoints in standard manners intended to disrupt service responsiveness. You may not misrepresent our source codes or host identical replicas under malicious parameters.
          </p>
        </div>

        {/* Term 5 */}
        <div className="p-5 sm:p-6 rounded-2xl border border-slate-200 dark:border-slate-850 bg-white dark:bg-slate-950">
          <h2 className="text-xs font-black uppercase tracking-widest text-slate-900 dark:text-white font-display mb-3">
            5. Revisions to Terms
          </h2>
          <p>
            We reserves the absolute freedom to refine these terms in response to technological expansions or operational changes. Continued visitations of the workspace or use of customized fallbacks constitute active consent to any amended conditions.
          </p>
        </div>

      </div>
    </div>
  );
}
